version: '3.7'

services:
  noteself:
    container_name: noteself
    image: danzig12/noteself:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - noteself-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: noteself
      POSTGRES_USER: noteself
      POSTGRES_DB: noteself

volumes:
  noteself-db:
